# Add configuration values here, as shown below.
#
# pusher_app_id: "2954"
# pusher_key: 7381a978f7dd7f9a1117
# pusher_secret: abdc3b896a0ffb85d373
# stripe_api_key: sk_test_2J0l093xOyW72XUYJHE4Dv2r
# stripe_publishable_key: pk_test_ro9jV5SNwGb1yYlQfzG17LHK
#
# production:
#   stripe_api_key: sk_live_EeHnL644i6zo4Iyq4v1KdV9H
#   stripe_publishable_key: pk_live_9lcthxpSIHbGwmdO941O1XVU

facebook_app_id: "261618660944198"
facebook_app_secret: "75d91aeb0506e0d22594734615dd0c2f"

S3_BUCKET_NAME: "amotest"
AWS_ACCESS_KEY_ID: "AKIAJGSEKIGBCMA35QNQ"
AWS_SECRET_ACCESS_KEY: "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"
AWS_REGION: "ap-northeast-1"

STRIPE_CONNECT_CLIENT_ID: "ca_AAK0NiKmYI7NqIY4BUremZ08PcyCSl66"
STRIPE_SECRET_KEY: "sk_test_LUjutRgIlq68WupRsdP3roBv"
STRIPE_PUBLISHABLE_KEY: "pk_test_KcmcIPyNmJgFC1L3xRmVWhVr"
